name: 5-Actions
on: workflow_dispatch
jobs:
  my-first-job:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
            distribution: 'adopt'
            java-version: '11'
      - run: mvn install
      - run: ls ./target
